name: Docker

on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - bdrmapit
          - chproxy
          - clickhouse-aarch64
          - flashroute
          - ipv4-heatmap
          - tippecanoe
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dioptra-io/publish-docker-action@v1.2
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          image: dioptra-io/docker-images/${{ matrix.image }}
          password: ${{ secrets.GITHUB_TOKEN }}
