name: Docker

on:
  push:
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "bdrmapit"
            platforms: linux/amd64,linux/arm64
          - image: "flashroute"
            platforms: linux/amd64
          - image: "ipv4-heatmap"
            platforms: linux/amd64,linux/arm64
          - image: "tippecanoe"
            platforms: linux/amd64,linux/arm64
          - image: "tracebox"
            platforms: linux/amd64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dioptra-io/publish-docker-action@v1
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          image: dioptra-io/docker-images/${{ matrix.image }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ matrix.platforms }}
